### PR TITLE
Add some breakout room details

### PR DESCRIPTION
**Pull request by jaclyn-taroni**
I didn't get a screenshot of the message banner last time I tested with breakout rooms, so I'm adding that here. Also adds info about the countdown prompt when all breakout rooms are closed (there's a 60 second countdown by default).

### CODE REVIEW

**Comment by cansavvy** [comment]
Are we gonna add the `Join Breakout Room` button here too? 

Screen Shot 2020-06-12 at 1 12 14 PM

**Comment by jaclyn-taroni** [comment]
I would consider that covered already: https://alexslemonade.github.io/2020-june-training/virtual-setup/zoom-procedures.html#joining-a-breakout-room These are some (more minor) details beyond what was added in #24.

**Comment by jaclyn-taroni** [comment]
Needs to be approved to 🚀

**Review by cansavvy — APPROVED** [review]
🎸 🎵

**Pull request merged**
